---
- name: Create VM frontend container
  docker_container:
    name: vm-frontend
    env:
      PORT: '{{ vm_frontend_port | string }}'
    image: '{{ vm_frontend_image }}'
    ports:
      - '{{ vm_frontend_port }}:{{ vm_frontend_port }}'
    pull: true
    read_only: true
    restart_policy: unless-stopped
    state: started
    volumes:
      - '{{ REPO }}/.env:/app/.env'
    working_dir: /app

- name: Cron job to run Ansible
  ansible.builtin.cron:
    name: Run Ansible
    cron_file: run-ansible
    user: root
    job: '/bin/sleep {{ 300 | random }}; {{ REPO }}/runme.sh > {{ REPO }}/logs/run-ansible.log 2>&1'
    minute: '2,17,32,47'
    hour: '*'

- name: Set net.core.rmem_max
  ansible.posix.sysctl:
    name: net.core.rmem_max
    value: '2500000'
    state: present
    sysctl_set: true
