---
- hosts: all
  gather_facts: true
  become: true
  vars:
    manage_docker: "{{ MANAGE_DOCKER | default('true') }}"
    manage_datadog: "{{ MANAGE_DATADOG | default('false') }}"
  tasks:
    - name: nodePlaybook | Update apt cache
      apt:
        update_cache: true
        cache_valid_time: '{{ 60 * 60 * 24 }}'
      tags:
        - always
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

    - name: nodePlaybook | Include geerlingguy.docker role
      include_role:
        name: geerlingguy.docker
        apply:
          tags:
            - docker
      vars:
        docker_apt_arch: "{{ { 'aarch64': 'arm64', 'x86_64': 'amd64' }[ansible_facts.architecture] }}"
        docker_compose_version: "v2.2.3"
        docker_users: "{{ DOCKER_USERS | default(['ubuntu']) }}"
        docker_daemon_options:
          log-driver: "local"
      tags:
        - always
      when: manage_docker | bool

    - name: nodePlaybook | include vm_frontend role
      include_role:
        name: vm_frontend
        apply:
          tags:
            - vm_frontend
      tags:
        - always

    - name: nodePlaybook | install DataDog
      include_role:
        name: datadog.datadog
        apply:
          tags:
            - datadog
      when: manage_datadog | bool        
      vars:
        datadog_api_key: "{{ DATADOG_API_KEY }}"
        site: us5.datadoghq.com