name: Docker CI

on:
  push:
    branches: [ master ]
    paths: [ 'Dockerfile','client/**','public/**','src/**','*.ts','*.json','.github/workflows/ci-docker.yml' ]
  pull_request:
    branches: [ master ]
    paths: [ 'Dockerfile','client','public/**','src/**','*.ts','*.json','.github/workflows/ci-docker.yml' ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: qemu
        uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
      - name: run
        run: docker run --read-only ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
