name: JavaScript CI

on:
  push:
    branches: [ master ]
    paths: [ 'client/**','src/**','*.ts','*.json','.github/workflows/ci-js.yml' ]
  pull_request:
    branches: [ master ]
    paths: [ 'client/**','src/**','*.ts','*.json','.github/workflows/ci-js.yml' ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 17.x]
        target: [client, server]
    defaults:
      run:
        shell: bash
        working-directory: ${{ matrix.target }}
    steps:
      - uses: actions/checkout@v2
      - name: install node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
        env:
          CI: false
      - run: npm test
