name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  ### TODO: uncomment me and check if serialization-lib broke us
  # build:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       node-version: [16.x, 17.x]
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: install node ${{ matrix.node-version }}
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version: ${{ matrix.node-version }}
  #     - run: npm ci
  #     - run: npm run build --if-present
  #     - run: npm test
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: qemu
        uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          ### TODO: test multiple platforms
          # platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  ansible:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ansible-community/ansible-lint-action@v6
        with:
          args: "ansible"
      - run: 'echo "VM_TOKEN=foo" > .env'
      - run: 'bash ./runme.sh'
